spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false

logging:
  level:
    org.hibernate.SQL: INFO
    com.marketplace.classifieds: INFO
